import { Express, Request, Response } from "express";
import fs from "fs";
import path from "path";
import { hashApiKey, validateKeyFormat, testShyftKey, testChainstackUrl } from "./key-validator";
import { upsertProxyConfig } from "./proxy-config-db";

interface SetupRequest {
  authPassword: string;
  shyftKey: string;
  chainstackUrl: string;
  proxyName?: string;
  proxyPort?: number;
  outboundIp?: string;
  pincher2Url?: string;
}

interface SetupResponse {
  success: boolean;
  message: string;
  error?: string;
  keyHashes?: {
    shyftKeyHash: string;
    chainstackUrlHash: string;
  };
}

/**
 * Register setup endpoints on the Express app
 * Called during startup if setup UI is needed
 */
export function registerSetupEndpoints(app: Express): void {
  /**
   * POST /api/setup/validate-keys - Validate API keys without saving
   */
  app.post("/api/setup/validate-keys", async (req: Request, res: Response) => {
    const { authPassword, shyftKey, chainstackUrl } = req.body as Partial<SetupRequest>;

    if (!authPassword || !shyftKey || !chainstackUrl) {
      return res.status(400).json({
        success: false,
        error: "Missing required fields: authPassword, shyftKey, chainstackUrl",
      } as SetupResponse);
    }

    try {
      // Validate formats
      const shyftFormat = validateKeyFormat(shyftKey, "shyft");
      if (!shyftFormat.valid) {
        return res.status(400).json({
          success: false,
          error: `Shyft key validation failed: ${shyftFormat.error}`,
        } as SetupResponse);
      }

      const chainstackFormat = validateKeyFormat(chainstackUrl, "chainstack");
      if (!chainstackFormat.valid) {
        return res.status(400).json({
          success: false,
          error: `Chainstack URL validation failed: ${chainstackFormat.error}`,
        } as SetupResponse);
      }

      // Test Shyft key
      const shyftTest = await testShyftKey(shyftKey);
      if (!shyftTest.works) {
        return res.status(400).json({
          success: false,
          error: `Shyft key test failed: ${shyftTest.error}`,
        } as SetupResponse);
      }

      // Test Chainstack URL
      const chainstackTest = await testChainstackUrl(chainstackUrl);
      if (!chainstackTest.works) {
        return res.status(400).json({
          success: false,
          error: `Chainstack endpoint test failed: ${chainstackTest.error}`,
        } as SetupResponse);
      }

      // All tests passed
      res.json({
        success: true,
        message: "✓ All API keys validated successfully",
        keyHashes: {
          shyftKeyHash: hashApiKey(shyftKey),
          chainstackUrlHash: hashApiKey(chainstackUrl),
        },
      } as SetupResponse);
    } catch (error) {
      res.status(500).json({
        success: false,
        error: `Validation error: ${error instanceof Error ? error.message : String(error)}`,
      } as SetupResponse);
    }
  });

  /**
   * POST /api/setup/save-pincher2-config - Save Pincher2 config to .env.pincher2
   */
  app.post("/api/setup/save-pincher2-config", (req: Request, res: Response) => {
    const { authPassword, shyftKey, chainstackUrl } = req.body as Partial<SetupRequest>;

    if (!authPassword || !shyftKey || !chainstackUrl) {
      return res.status(400).json({
        success: false,
        error: "Missing required fields",
      } as SetupResponse);
    }

    try {
      const envContent = `# Pincher2 Configuration
# Generated by setup wizard

PROXY_AUTH_PASSWORD=${authPassword}
SHYFT_API_KEY=${shyftKey}
CHAINSTACK_RPC_URL=${chainstackUrl}

NODE_ENV=production
`;

      const envPath = path.join(process.cwd(), ".env.pincher2");
      fs.writeFileSync(envPath, envContent, "utf-8");

      res.json({
        success: true,
        message: "✓ Pincher2 configuration saved to .env.pincher2",
        keyHashes: {
          shyftKeyHash: hashApiKey(shyftKey),
          chainstackUrlHash: hashApiKey(chainstackUrl),
        },
      } as SetupResponse);
    } catch (error) {
      res.status(500).json({
        success: false,
        error: `Failed to save config: ${error instanceof Error ? error.message : String(error)}`,
      } as SetupResponse);
    }
  });

  /**
   * POST /api/setup/save-proxy-config - Save proxy config to .env.proxy-N and database
   */
  app.post("/api/setup/save-proxy-config", async (req: Request, res: Response) => {
    const {
      proxyName,
      proxyPort,
      outboundIp,
      pincher2Url,
      authPassword,
      shyftKey,
      chainstackUrl,
    } = req.body as Partial<SetupRequest>;

    if (
      !proxyName ||
      !proxyPort ||
      !outboundIp ||
      !pincher2Url ||
      !authPassword ||
      !shyftKey ||
      !chainstackUrl
    ) {
      return res.status(400).json({
        success: false,
        error: "Missing required fields",
      } as SetupResponse);
    }

    try {
      const shyftKeyHash = hashApiKey(shyftKey);
      const chainstackUrlHash = hashApiKey(chainstackUrl);

      // Write .env.proxy-N file
      const envContent = `# Proxy ${proxyName} Configuration
# Generated by setup wizard

PROXY_NAME=${proxyName}
PROXY_PORT=${proxyPort}
OUTBOUND_IP=${outboundIp}
PINCHER2_URL=${pincher2Url}
PROXY_AUTH_PASSWORD=${authPassword}
SHYFT_API_KEY=${shyftKey}
CHAINSTACK_RPC_URL=${chainstackUrl}

NODE_ENV=production
`;

      const envFileName = `.env.${proxyName}`;
      const envPath = path.join(process.cwd(), envFileName);
      fs.writeFileSync(envPath, envContent, "utf-8");

      // Store in database (requires database connection)
      try {
        await upsertProxyConfig({
          proxyName,
          outboundIp,
          port: proxyPort,
          status: "idle",
          shyftKeyHash,
          chainstackUrlHash,
        });
      } catch (dbError) {
        console.warn("[Setup] Database save skipped (db not initialized yet):", dbError);
      }

      res.json({
        success: true,
        message: `✓ Proxy configuration saved to ${envFileName}`,
        keyHashes: {
          shyftKeyHash,
          chainstackUrlHash,
        },
      } as SetupResponse);
    } catch (error) {
      res.status(500).json({
        success: false,
        error: `Failed to save proxy config: ${error instanceof Error ? error.message : String(error)}`,
      } as SetupResponse);
    }
  });

  /**
   * GET /api/setup/check-config - Check if config files exist
   */
  app.get("/api/setup/check-config", (_req: Request, res: Response) => {
    try {
      const pincher2Exists = fs.existsSync(path.join(process.cwd(), ".env.pincher2"));
      const proxy1Exists = fs.existsSync(path.join(process.cwd(), ".env.proxy-1"));
      const proxy2Exists = fs.existsSync(path.join(process.cwd(), ".env.proxy-2"));
      const proxy3Exists = fs.existsSync(path.join(process.cwd(), ".env.proxy-3"));

      res.json({
        pincher2Configured: pincher2Exists,
        proxiesConfigured: {
          "proxy-1": proxy1Exists,
          "proxy-2": proxy2Exists,
          "proxy-3": proxy3Exists,
        },
        proxiesCount: [proxy1Exists, proxy2Exists, proxy3Exists].filter(Boolean).length,
      });
    } catch (error) {
      res.status(500).json({
        error: `Failed to check config: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  });

  /**
   * GET /setup - Serve setup UI (static HTML or React SPA)
   */
  app.get("/setup", (_req: Request, res: Response) => {
    res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Penny-Pincher2 Setup Wizard</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f0f0f; color: #fff; }
        .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
        .header { text-align: center; margin-bottom: 40px; }
        .header h1 { font-size: 2em; margin-bottom: 10px; }
        .header p { color: #888; }
        .form-group { margin-bottom: 20px; }
        label { display: block; font-weight: 500; margin-bottom: 8px; }
        input, textarea { width: 100%; padding: 10px; border: 1px solid #333; background: #1a1a1a; color: #fff; border-radius: 4px; font-family: monospace; }
        input:focus, textarea:focus { outline: none; border-color: #00d4ff; }
        button { background: #00d4ff; color: #000; padding: 12px 24px; border: none; border-radius: 4px; font-weight: 600; cursor: pointer; }
        button:hover { background: #00b8cc; }
        .status { padding: 12px; border-radius: 4px; margin-top: 10px; }
        .status.success { background: #1a3a1a; color: #00ff00; }
        .status.error { background: #3a1a1a; color: #ff6b6b; }
        .status.loading { background: #2a2a2a; color: #00d4ff; }
        .tabs { display: flex; gap: 10px; margin-bottom: 30px; border-bottom: 1px solid #333; }
        .tab { padding: 12px 20px; cursor: pointer; border-bottom: 2px solid transparent; color: #888; }
        .tab.active { color: #00d4ff; border-color: #00d4ff; }
        .tab-content { display: none; }
        .tab-content.active { display: block; }
        .note { background: #1a2a3a; padding: 12px; border-radius: 4px; margin: 10px 0; font-size: 0.9em; color: #aaa; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🖥️ Penny-Pincher2 Setup Wizard</h1>
            <p>Configure authentication and API keys before startup</p>
        </div>

        <div class="tabs">
            <div class="tab active" onclick="switchTab('pincher2')">Pincher2</div>
            <div class="tab" onclick="switchTab('proxies')">Proxies</div>
        </div>

        <!-- Pincher2 Tab -->
        <div id="pincher2" class="tab-content active">
            <h2>Pincher2 Server Configuration</h2>
            <div class="form-group">
                <label>Proxy Auth Password (shared secret)</label>
                <input type="password" id="authPassword" placeholder="e.g., secure-random-password-123">
                <div class="note">This password is shared with all proxies. Use a strong, random value.</div>
            </div>

            <div class="form-group">
                <label>Shyft API Key</label>
                <input type="text" id="pincher2ShyftKey" placeholder="Your Shyft API key">
                <div class="note">Free tier available at shyft.to. Used for token metadata.</div>
            </div>

            <div class="form-group">
                <label>Chainstack RPC Endpoint (Free Tier)</label>
                <input type="text" id="pincher2ChainstackUrl" placeholder="https://solana-mainnet.core.chainstack.com/...">
                <div class="note">Get free tier from chainstack.com. No paid upgrades.</div>
            </div>

            <button onclick="validateAndSavePincher2()">Validate & Save Configuration</button>
            <div id="pincher2Status"></div>
        </div>

        <!-- Proxies Tab -->
        <div id="proxies" class="tab-content">
            <h2>Proxy Configuration</h2>
            <div class="note">Configure each proxy (1-3) on separate machines with unique IPs and API keys.</div>

            <div id="proxyForms"></div>
            <button onclick="addProxyForm()">+ Add Proxy</button>

            <div id="proxiesStatus"></div>
        </div>
    </div>

    <script>
        function switchTab(tab) {
            document.querySelectorAll('.tab-content').forEach(el => el.classList.remove('active'));
            document.querySelectorAll('.tab').forEach(el => el.classList.remove('active'));
            document.getElementById(tab).classList.add('active');
            event.target.classList.add('active');
        }

        async function validateAndSavePincher2() {
            const authPassword = document.getElementById('authPassword').value;
            const shyftKey = document.getElementById('pincher2ShyftKey').value;
            const chainstackUrl = document.getElementById('pincher2ChainstackUrl').value;

            if (!authPassword || !shyftKey || !chainstackUrl) {
                showStatus('pincher2Status', '❌ All fields are required', 'error');
                return;
            }

            showStatus('pincher2Status', '⏳ Validating keys...', 'loading');

            try {
                const validateRes = await fetch('/api/setup/validate-keys', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ authPassword, shyftKey, chainstackUrl })
                });

                if (!validateRes.ok) {
                    const error = await validateRes.json();
                    showStatus('pincher2Status', '❌ ' + error.error, 'error');
                    return;
                }

                const validated = await validateRes.json();
                showStatus('pincher2Status', '✓ Keys validated. Saving...', 'loading');

                const saveRes = await fetch('/api/setup/save-pincher2-config', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ authPassword, shyftKey, chainstackUrl })
                });

                if (!saveRes.ok) {
                    throw new Error('Failed to save config');
                }

                showStatus('pincher2Status', '✅ Configuration saved! You can now configure proxies.', 'success');
            } catch (err) {
                showStatus('pincher2Status', '❌ ' + err.message, 'error');
            }
        }

        function addProxyForm() {
            const container = document.getElementById('proxyForms');
            const count = container.children.length + 1;
            const form = document.createElement('div');
            form.innerHTML = \`
                <div style="background: #1a1a1a; padding: 20px; border-radius: 4px; margin-bottom: 20px;">
                    <h3>Proxy \${count}</h3>
                    <div class="form-group">
                        <label>Proxy Name</label>
                        <input type="text" value="proxy-\${count}" placeholder="proxy-1">
                    </div>
                    <div class="form-group">
                        <label>Port</label>
                        <input type="number" value="\${3000 + count}" placeholder="3001">
                    </div>
                    <div class="form-group">
                        <label>Outbound IP</label>
                        <input type="text" placeholder="Will auto-detect if empty">
                    </div>
                    <div class="form-group">
                        <label>Pincher2 URL</label>
                        <input type="text" placeholder="http://pincher2-ip:5000">
                    </div>
                    <div class="form-group">
                        <label>Shyft API Key (unique)</label>
                        <input type="text" placeholder="Must differ from other proxies">
                    </div>
                    <div class="form-group">
                        <label>Chainstack RPC Endpoint (unique)</label>
                        <input type="text" placeholder="Must differ from other proxies">
                    </div>
                    <button onclick="validateAndSaveProxy(this)">Validate & Save Proxy \${count}</button>
                </div>
            \`;
            container.appendChild(form);
        }

        async function validateAndSaveProxy(button) {
            const form = button.parentElement;
            const inputs = form.querySelectorAll('input');
            const proxyName = inputs[0].value;
            const proxyPort = parseInt(inputs[1].value);
            const outboundIp = inputs[2].value;
            const pincher2Url = inputs[3].value;
            const shyftKey = inputs[4].value;
            const chainstackUrl = inputs[5].value;

            if (!proxyName || !proxyPort || !pincher2Url || !shyftKey || !chainstackUrl) {
                showStatus('proxiesStatus', '❌ All fields except IP are required', 'error');
                return;
            }

            showStatus('proxiesStatus', '⏳ Validating proxy...', 'loading');

            try {
                const validateRes = await fetch('/api/setup/validate-keys', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ authPassword: '', shyftKey, chainstackUrl })
                });

                if (!validateRes.ok) {
                    const error = await validateRes.json();
                    showStatus('proxiesStatus', '❌ ' + error.error, 'error');
                    return;
                }

                const saveRes = await fetch('/api/setup/save-proxy-config', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        proxyName, proxyPort, outboundIp: outboundIp || 'auto-detect',
                        pincher2Url, authPassword: document.getElementById('authPassword').value,
                        shyftKey, chainstackUrl
                    })
                });

                if (!saveRes.ok) throw new Error('Failed to save');
                showStatus('proxiesStatus', '✅ Proxy ' + proxyName + ' configured!', 'success');
            } catch (err) {
                showStatus('proxiesStatus', '❌ ' + err.message, 'error');
            }
        }

        function showStatus(elementId, message, type) {
            const el = document.getElementById(elementId);
            el.textContent = message;
            el.className = 'status ' + type;
        }

        // Initialize with first proxy form
        addProxyForm();
    </script>
</body>
</html>
    `);
  });
}

export default registerSetupEndpoints;
